name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t gaumji19/selenium:latest .
          docker tag gaumji19/selenium:latest gaumji19/selenium:${{ github.run_number }}
          docker push gaumji19/selenium:latest
          docker push gaumji19/selenium:${{ github.run_number }}

      - name: Trigger Test Workflow
        if: success()
        run: |
          curl -X POST https://api.github.com/repos/SithScripter/selenium-docker-runner-ghactions/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GH_TOKEN" \
          -d '{"event_type": "run-tests", "client_payload": { "browser": "chrome" }}'
          
